name: aje
favicon: null
layout_spectrum: 0.3035225498024374
typography_spectrum: 0.6103
title: AJE Creative LLC.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fc8901'
    - '#666666'
    - '#000000'
    - '#fa3c01'
    - '#333300'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.0625
  rhythmicContrast: 0.25
purpose: []
